- .github/install-etcd.sh
- .github/workflows/build-and-push.yml
- .github/workflows/unit-test.yml
- Dockerfile
- src/test/java/com/ibm/watson/modelmesh/ModelMeshTearDownTest.java
- There is a unit test workflow for gating pull requests.
- Then there is also a workflow that, on each push, runs tests then builds/pushes to docker hub if the tests pass.
- The `command` was removed from the ModelMeshTearDown test because the test would fail with `no such file or directory` for `command`.
Note, tests are not run from the `docker build` command because of the `-DskipTests=true` in the `mvn` command in the Dockerfile. Removing the `skipTests` flag and running the tests during the image build always fails in the GitHub Actions environment after the tests complete due to connection time outs. 
Ex:
```
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 49, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ model-mesh --- …
```
> Update Github workflows to run unit tests

- .github/workflows/build-and-push.yml
We want version tagged docker images to be pushed to DockerHub when a new release is tagged in GitHub.
Adjusted the workflow file to also test, build, and push the image on tags.
Tagged image versions on DockerHub.
> chore: Add release tag workflow

- pom.xml
Using model-mesh as a maven artifact is a legacy “library integration” case which we should consider deprecated. Currently we are not deploying the maven artifact even so we do not need this.
> chore: remove distribution management from maven

- pom.xml
- log4j 2.15.0
- netty 4.1.71.Final, netty-tcnative 2.0.46.Final
- eclipse-collections 11.0.0
- junit 5.8.2
Signed-off-by: nickhill <nickhill@us.ibm.com>
> deps: Update dependencies including important log4j CVE fix

- pom.xml
- src/main/java/com/ibm/watson/modelmesh/ModelCacheUnloadBufManager.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/clhm/ConcurrentLinkedHashMap.java
- src/test/java/com/ibm/watson/modelmesh/EvictionsModelMeshTest.java
- src/test/java/com/ibm/watson/modelmesh/example/Model.java
This is _really_ expected to be the final sync of IBM-internal fixes, future PRs will be made directly against this repo.
> Internal sync

- src/main/java/com/ibm/watson/modelmesh/Metric.java
The prometheus exposition format can include per-metric help text, it was always a TODO to add more useful descriptions for all of the emitted model-mesh metrics.
Add text descriptions for each of the published prometheus metrics.
Better discoverability for model-mesh prometheus metrics.
> feat: Include prometheus metric help text

- src/main/java/com/ibm/watson/modelmesh/ModelCacheUnloadBufManager.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/clhm/ConcurrentLinkedHashMap.java
- src/test/java/com/ibm/watson/modelmesh/SidecarModelMeshTest.java
A recent fix for a cascading eviction race condition introduced the possibility of a deadlock between the model cache lock and per-cache entry locks due to eviction callback logic now performed in-line under the cache lock.
Rework cache accounting logic to make an eviction/unload related adjustment unconditionally up-front within the cache lock so that it can be released before the entry removal/unload processing is performed along with state-dependent readjustment if necessary.
Also:
- Ensure all entry weight updates are guarded by the cache lock
- Change the cache's `oldestTime()` method to not take the cache lock since it's used on the inference request path
Hopefully no more deadlocks
> fix: Fix for eviction deadlock

- src/main/java/com/ibm/watson/modelmesh/GrpcSupport.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/StaticModelRegistration.java
- src/main/java/com/ibm/watson/modelmesh/VModelManager.java
Some internal requests to trigger model loads are done with no timeout. This had never been an issue because the remote processing is async in nature but it's best to have a safeguard timeout just in case these calls hang for some reason (as was observed in relation to a separate now-fixed deadlock bug).
- Add 3 second timeout for the internal `ensureLoaded` calls and ensure that `ensureLoadedInternal()` is used consistently for these
- Improve exception/logging messages related to timeouts (in particular avoid misleading "Unexpected internalOperation" messages)
- Add a new "in-" thread name prefix to distinguish from "ex-" where the request originates internally
Internal remote request threads can't hang indefinitely.
> fix: Timeouts on all internal requests; better timeout logging

- src/main/java/com/ibm/watson/modelmesh/SidecarModelMesh.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshAllowAnyMethodTest.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshRefreshMissingModelTest.java
- src/test/java/com/ibm/watson/modelmesh/example/ExampleModelRuntime.java
By default, model-mesh transparently forwards any gRPC service requests to back-end runtimes based on model id headers. These calls will work as long as the runtime implements the target service method. However, runtimes might also expose the internal model management methods on the same port and these are intended for model-mesh's internal use only. Currently they could be accessed directly from the outside in this case which could pose a security risk.
It's already possible to lock down which service methods are permitted at both the inside and outside service boundaries, but there's legitimate cases where it's more convenient to allow any methods and just have the runtime reject if unimplemented. So we should unconditionally block internal management service methods (with service name …
> fix: Always block internal management RPCs when on inference path

- pom.xml
jackson-databind `3.13.2.1` fixes CVE-2020-36518
> chore: Update dependencies including jackson CVE fix

- pom.xml
The update to etcd-java includes a fix that should result in a noticeable reduction in memory (heap) use for large model registries.
> deps: Update etcd-java, protobuf dependencies

- pom.xml
- grpc-java `1.46.0`
- netty `4.1.46.Final`
- protobuf `3.20.1`
> deps: Update grpc, netty, protobuf dependencies

- src/main/scripts/start.sh
Modelmesh can have problems in FIPS-enabled environments due to restrictions placed on TLS keystores.
Disable FIPS in RedHat OpenJDK via the `-Dcom.redhat.fips=false` command line arg, unless already specified in the `CUSTOM_JVM_ARGS` env var.
Modelmesh will continue to work in FIPS-enabled environments.
> fix: Disable FIPS for java

- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
Some model records were observed in the registry with an invalid `lastUsed` time of `Long.MAX_VALUE`, effectively pinning them at the front of the cache and causing them to remain loaded even if not used.
It's not clear whether the bug causing this has yet been fixed - for now we'll repair the entries and can monitor logs for the warning message below.
Add a check in the reaper loop over all models in the registry, and update invalid records with a `lastUsed` time of "3 hours ago".
Avoid "stuck" models due to incorrect `lastUsed` time.
> fix: Repair invalid ModelRecord lastUsed values in registry

- src/main/java/com/ibm/watson/modelmesh/InstanceRecord.java
- src/main/java/com/ibm/watson/modelmesh/InstanceSetStatsTracker.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/TypeConstraintManager.java
- src/main/java/com/ibm/watson/modelmesh/Utils.java
Some places in the modelmesh logs could do with additional information to help with debugging problems at runtime.
- Small refactor of "prohibited type sets" used in the type constraint logic to use a dedicated immutable class rather than raw string array
- Include hex hashcode in its `toString` output so that distinguishing distinct PTSs in log output is easier
- Log a warning with relevant diagnostic info when a model load is blocked for some reason other than loading failure
Slightly clearer code, easier diagnosis of runtime problems in some cases.
> logs: Some logging improvements for better problem diagnosis

- src/main/java/com/ibm/watson/modelmesh/Metric.java
- src/main/java/com/ibm/watson/modelmesh/Metrics.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java
- src/main/java/com/ibm/watson/prometheus/NettyServer.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshMetricsTest.java
Model-mesh already exposes a number of useful metrics but it would be useful to also monitor the size of requests and responses.
- Add new `modelmesh_request_size_bytes` and `modelmesh_response_size_bytes` metrics which use a new `MESSAGE_SIZE_HISTO` histogram definition with buckets more suited to typical message sizes
- Generalize existing `logApplyMethodTookNanosMetric()` method to log all request-specific metrics (including these new ones) and rename to `logRequestMetrics()`
- Change current behaviour where prometheus request metrics were not logged for non-success response codes
- Add basic unit test for prometheus metrics
Request and response payload sizes can be easily tracked along with other operational metrics.
> feat: Add metrics for inference request/response payload sizes

- Dockerfile
- src/main/scripts/start.sh
ModelMesh previously used the Concurrent Mark Sweep (CMS) garbage collector, chosen based on tuning done some time ago. The CMS collector was removed in Java 14 so can't be used now that we have moved to Java 17.
- Revert container start script to start modelmesh with the G1 garbage collector
- Ensure hostname command is available in container (used by start script in non-Kubernetes case)
We may later switch to a different collector such as Shenandoah, depending on results of performance comparisons.
ModelMesh container image works again
> fix: Switch to use G1 garbage collector

- src/main/proto/current/model-runtime.proto
In the model server gRPC service provider interface, implementation of the `predictModelSize` RPC is optional, and `modelSize` doesn't need to be implemented if sizes are always returned in the `loadModel` response.
This is documented in the [modelmesh docs](https://github.com/kserve/modelmesh-serving/blob/main/docs/runtimes/custom_runtimes.md#model-sizing) but not in the comments of the service .proto file.
Add appropriate wording to doc comments in the `model-runtime.proto` file to convey the fact these rpcs aren't required.
Clearer docs
> docs: Indicate which model-runtime proto SPI rpcs are optional

- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshEvictionsTest.java
Model-mesh will currently ensure that there's two copies of any model which has been used "recently" to make them "HA" and minimize the chance of disruption if a single pod dies. However this has recently proved problematic in one case involving a periodic invocation of a large number of models (for example once per day). Second copies of all are loaded within a small timeframe, filling the cache and evicting other recently-used models. In this case there's little value in having second copies since the usage is isolated.
A better heuristic is needed for deciding when redundant copies should be added.
- Remove the current logic related to second-copy triggering. This includes methods invoked on the inference request path and from the regular janitor task.
- Piggy-back on the existing …
> feat: Rework second-copy scaling logic

- pom.xml
grpc, kv-utils, etcd-java, protobuf, gson, junit
The kv-utils 0.5.1 update contains a fix to allow model-mesh to work properly with a shared, role-based-auth partitioned etcd cluster.
> deps: Refresh dependencies

- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
Somehow I failed to push a prepared final commit to #49's branch before it was merged. Embarrassingly this includes removal of a stdout debug message.
- Adjust min LRU for second copy scaleup: Make it a function of `SECOND_COPY_MAX_AGE_SECS` to ensure that there won't be flip-flopping with scaling down
- Remove spurious debug sysout
Second copy scaling thresholds should be better aligned, stop debug messages spewing to stdout.
> fix: Adjustments/cleanup missed from prior PR #49

- Dockerfile
The Dockerfile installs some packages that aren't needed
- Remove no-longer-used python related dependencies from build and release stages of docker build
- Bump `ubi-minimal` base image version to 8.6
Faster build, smaller images
> build: Clean up unused packages from docker image build

- pom.xml
- src/main/java/com/ibm/watson/modelmesh/Metrics.java
- src/main/java/com/ibm/watson/prometheus/NettyMemoryExports.java
- src/main/java/com/ibm/watson/prometheus/hotspot/BufferPoolsExports.java
- src/main/java/com/ibm/watson/prometheus/hotspot/GarbageCollectorExports.java
- src/main/java/com/ibm/watson/prometheus/hotspot/MemoryAllocationExports.java
- src/main/java/com/ibm/watson/prometheus/hotspot/MemoryPoolsExports.java
- src/main/scripts/start.sh
- src/test/java/com/ibm/watson/modelmesh/ModelMeshMetricsTest.java
To size model-mesh container memory allocation for different workloads, it would be useful to have more detailed usage metrics exposed.
Container process level memory usage alone is opaque and may reflect over-allocation of heap and/or direct buffer pools.
- Cherry pick some of the prometheus hotspot exporters from https://github.com/prometheus/client_java/tree/main/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot, and reduce the amount of garbage they produce during collection.
- Add a netty memory exporter which includes metrics for the amount of OS memory allocated for buffer pools as well as how much of that pool capacity is currently allocated to application buffers (for both heap and direct arenas, although typically only direct should be used).
- Enable these by …
> feat: Expose detailed JVM and netty memory metrics

- pom.xml
grpc `1.50.0`, netty `4.1.84.Final`
The netty update contains some nice performance improvements.
> deps: Update gRPC and netty dependencies

- pom.xml
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/thrift/ModelMeshService.java
- src/main/thrift/modelmesh.thrift
- src/test/java/com/ibm/watson/modelmesh/AbstractModelMeshClusterTest.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshErrorPropagationTest.java
- src/test/java/com/ibm/watson/modelmesh/example/ExampleModelRuntime.java
In certain error edge cases, `InternalException`s can be thrown on the inferencing path, but these currently don't propagate properly because they aren't declared to be thrown by the internal thrift `applyModel(Multi)` method. Because of this, they are treated as generic errors meaning that the error detail (message) is lost and when returned to the user can have a confusing message like "Nowhere available to load".
Furthermore, there was a bug when checking the type of remote exceptions, where in certain places they were not first being unwrapped as intended.
- Add `InternalException` to internal `applyModel` thrift rpc method definitions
- Ensure remote exceptions to be examined are unwrapped from `InvocationTargetException` first
- Add unit test for this case
- Also update to use …
> fix: Ensure intra-cluster InternalExceptions are propagated properly

- src/main/scripts/start.sh
A bug was introduced in recent PR https://github.com/kserve/modelmesh/pull/61 resulting in the netty direct memory pool size not being set correctly.
Add missing `$` to variable in bash if condition in start.sh
Correct netty direct memory allocation size, avoid OOM crashing.
> fix: Fix direct memory allocation config

- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/ModelMeshEnvVars.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshFailureExpiryTest.java
- src/test/java/com/ibm/watson/modelmesh/SidecarModelMeshTest.java
- src/test/java/com/ibm/watson/modelmesh/example/Model.java
A bug was encountered whereby model load failure records would not be cleaned up after expiration while there were continuous (failing) requests for that model, meaning no reload attempt occurred and those requests failed indefinitely.
- Add unit test to reproduce the problem, which required
- Making expiry time configurable
- Modifying the behaviour of the dummy model so that triggered loading failures only occur on the first attempt
- Add some log statements
- Fix the main bug: When a failed cache entry without any record in the registry is encountered during a load attempt, remove it rather than treating as a load failure
- Fix some other logic related to failure expiry
- Use a shorter expiry time (2/3 of configured time) for recently-requested models
Failures expire as intended in all …
> fix: Fix failure expiry race condition

- src/main/java/com/ibm/watson/modelmesh/Metrics.java
`fq_names` is a boolean sub-parameters that can be used to alter the metrics exposed by model-mesh. Unfortunately however its value is inverted, so setting it to "true" actually disables fully qualified method names (which is already the default).
Change to interpret anything other than false as enabling (default is still disabled).
Metrics configuration behaves as expected.
> fix: Fix fq_names metrics parameter

- src/main/java/com/ibm/watson/modelmesh/Metrics.java
Follow up to PR #75, use short names (by default) unless `fq_names` is set to `true`
Correct the boolean expression that sets `shortNames` based on the negated `fq_names` parameter value.
Brief example to illustrate the behavior after this code change:
```Java
String[] fq_names_values = {"true", "True", "TRUE", "false", "False", "FALSE", "", "off", "on", "N/A"};
for (String fq_names_value: fq_names_values) {
boolean shortNames = !"true".equalsIgnoreCase(fq_names_value);
System.out.println("fq_names='%s' => shortNames=%s".formatted(fq_names_value, shortNames));
}
```
```
fq_names='true' => shortNames=false
fq_names='True' => shortNames=false
fq_names='TRUE' => shortNames=false
fq_names='false' => shortNames=true
fq_names='False' => shortNames=true
fq_names='FALSE' => shortNames=true …
```
> fix: `fq_names` parameter check

- src/main/java/com/ibm/watson/modelmesh/ModelCacheUnloadBufManager.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
Some issues have been observed in production where the cache appears to get into a broken state, including a cascading eviction of all models.
- Fix cache accounting in loading failure + unload case
- Eagerly remove expired failure records from cache
- Correct misworded log message
- Log some internal cache values along with published instance records, to facilitate further diagnoses
- Increase load failure expiry times
Hopefully fixed cache accounting issue
> fix: Fix cache accounting in loading failures case

- .github/workflows/build-and-push.yml
Feature parity with kserve and knative ref https://github.com/kserve/kserve/pull/2550#discussion_r1055222609
Fixes https://github.com/kserve/kserve/issues/2612
- Now runs `test` job on PR
- Now pushes multi-arch docker images on `push`
Can run on e.g. AWS graviton family instances (arm64)
> Push multi-arch docker image

- .github/workflows/build-and-push.yml
This reverts commit d9892e3df7605e378b3076979ae75f9fc0040dd8.
These changes actually broke our main image build. Unfortunately the actions that run on the PR don't actually build the image. @ckadner is addressing that and then we can reopen this if needed post 0.10 release.
@ddelange it probably only makes sense anyhow if we do this for all the modelmesh images i.e. also including `modelmesh-serving` and `modelmesh-runtime-adapter`
> Revert "Push multi-arch docker image (#76)"

- pom.xml
- src/main/java/com/ibm/watson/modelmesh/Metrics.java
- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/main/java/com/ibm/watson/modelmesh/ModelMeshEnvVars.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshMetricsTest.java
Allow the generation of an "info" metric by way of environment variables captured as `Gauge` metric set up during container startup
- Added environment variable `MMESH_CUSTOM_ENV_VAR` in `ModelMeshEnvVars`
- Added map `infoMetricParams` and logic to parse and pass the info to prometheus in `ModelMesh`
- Added a `Gauge` using the parsed label names and values in `Metrics`
- Added sample variables to `pom.xml` for testing and related test in `ModelMeshMetricsTest`
- Support to pass information by via environment variables parsed as `<metricname>[;label1=envVarWithValueforLabel1,label2=envVarWithValueforLabel2,...,labelN=envVarWithValueforLabelN,]` if provided.
> feat: Allow custom prometheus info metric

- .dockerignore
- .github/workflows/build.yml
- Dockerfile
- README.md
Fix multi-platform build introduced in PR #80
Don't use "default" for `ARG`s `TARGETOS` and `TARGETARCH` in `Dockerfile`.
Images of [`kserve/modelmesh`](https://hub.docker.com/r/kserve/modelmesh/tags) for platforms `linux/amd64`, `linux/arm64`, `linux/ppc64le`.
- https://github.com/kserve/modelmesh/pull/80
- https://github.com/kserve/modelmesh-minio-examples/pull/3
- https://github.com/kserve/modelmesh-runtime-adapter/pull/38
- https://github.com/kserve/modelmesh-serving/pull/314
- https://github.com/kserve/rest-proxy/pull/24
- https://github.com/kserve/modelmesh-serving/pull/371
> Fix multi-platform build

- src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java
Some ByteBuf leak errors were reported in a production deployment of model-mesh as described in https://github.com/kserve/modelmesh/issues/97.
In `ModelMeshApi`, ensure that the response is released if a runtime exception is thrown prior to it being sent successfully.
Hopefully leak closed
> fix: Fix possible exception-related ByteBuf leak

- src/main/scripts/start.sh
Docker image was not picking up memory limits when cgroup v2 was used. This lead to incorrect java heap memory limits that lead to crashes due to OOMKilled as described in #106 
To `start.sh` script that launches application added extra check for limits in [cgroup](https://kubernetes.io/docs/concepts/architecture/cgroups/) v2 file.
Docker image works and correctly reads memory limits with both cgroup [v1](http://old-releases.ubuntu.com/releases/) and v2.
> fix: Fix not reading limits when cgroup v2 used

- pom.xml
- src/test/java/com/ibm/watson/modelmesh/AbstractModelMeshTest.java
- src/test/java/com/ibm/watson/modelmesh/LegacyAddRemoveProtoTest.java
- src/test/java/com/ibm/watson/modelmesh/LegacyTasProtoTest.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshHeaderLoggingTest.java
- src/test/java/com/ibm/watson/modelmesh/VModelsTest.java
- src/test/java/com/ibm/watson/modelmesh/example/ExampleModelClient.java
grpc, protobuf, guava, jackson-databind, thrift, log4j2, junit
> deps: Update various dependencies

- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
- src/test/java/com/ibm/watson/modelmesh/ModelMeshTearDownTest.java
This PR makes the following changes:
- Execute external commands using an array of strings rather than a single string as per https://github.com/kserve/modelmesh/security/code-scanning/2 
- Make the regular expression pattern a bit more efficient
https://github.com/kserve/modelmesh/security/code-scanning/1
> fix: Avoid string concat and regex inefficiency

- pom.xml
chore: Update bouncy castle depdendency to address the following vulnerability:
- [CVE-2023-33201](https://nvd.nist.gov/vuln/detail/CVE-2023-33201): Bouncy Castle For Java LDAP injection vulnerability
> Address bounce castle cve alert

- docs/metrics.md
> docs: Add `per_model_metrics` parameter to metrics.md

- src/main/java/com/ibm/watson/modelmesh/Metrics.java
#90 introduced support for per-model prometheus metrics but the intention was not to change the default behaviour and have this as something enabled explicitly via configuration.
However, it was inadvertently made the default.
Change default behaviour to not include modelId/vModelId prometheus metric labels. This is important because model-mesh was designed primarily for use cases where there is a very large and changing number of individual models and those scenarios would result in a much greater number of individual metrics than prometheus can handle.
Original behaviour restored
> fix: Per-model metrics labels should be disabled by default

- src/main/scripts/start.sh
This won't change current behaviour since the default is to use netty's openssl-based TLS implementation anyhow. But it will allow overriding to use the native jdk TLS impl when needed.
> fix: Remove explicit arg that enables litelinks' use of openssl

- pom.xml
protobuf 3.25.0, jackson-databind 2.16.0, junit 5.10.1, etcd-java 0.0.24
Includes important etcd-java update to support authentication when using etcd server versions >= 3.5
Unfortunately latest netty 4.1.101.Final is incompatible with grpc-java. We'll need to wait for a grpc patch for that.
> deps: Update dependencies

- Dockerfile
chore: update ubi8-minimal to latest version, 8.8. Vulnerabities fixed:
- [RHSA-2023:7165]( https://access.redhat.com/errata/RHSA-2023:7151): cups security and bug fix update (Moderate)
- [RHSA-2023:7151](https://access.redhat.com/errata/RHSA-2023:7151): python3 security update (Moderate)
- [RHSA-2023:7176](https://access.redhat.com/errata/RHSA-2023:7176): python-pip security update (Moderate)
- [RHSA-2023:7151](https://access.redhat.com/errata/RHSA-2023:7151): python3 security update (Moderate)
- [RHSA-2023:7190](https://access.redhat.com/errata/RHSA-2023:7190): avahi security update (Moderate)
- [RHSA-2023:7112](https://access.redhat.com/errata/RHSA-2023:7112): shadow-utils security and bug fix update (Low)
> Bump ubi8 tag to 8.8

- src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java
An issue was reported in #111 where response payloads logged by a configured `PayloadProcessor` were sometimes incorrectly empty.
Do not attempt to avoid slicing the response bytebuf in the case that a `PayloadProcessor` is configured, do not attempt to avoid some additional refcount updates in status != OK case.
Hopefully no more incorrectly empty logged payloads
Resolves #111
> fix: Fix PayloadProcessor response payload race condition

- src/main/java/com/ibm/watson/modelmesh/ModelMeshApi.java
- src/main/java/com/ibm/watson/modelmesh/payload/MatchingPayloadProcessor.java
- src/main/java/com/ibm/watson/modelmesh/payload/Payload.java
- src/main/java/com/ibm/watson/modelmesh/payload/RemotePayloadProcessor.java
Currently the payloads passed to PayloadProcessors only contain the modelId, which in the case of vModels will be a "resolved" modelId corresponding to a particular model revision (in particular this will be true when used in KServe modelmesh-serving). It would be useful to include the vModelId too.
Add a `vModelId` field to the `Payload` class and correspondingly update built-in `PayloadProcessor` implementations where applicable.
It may be null if the request was directed at a concrete modelId rather than a vModelId.
Both modelId and vModelId are available to PayloadProcessors
> feat: Add vModelId to PayloadProcessor Payload

- src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
Help debugging unready condition of modelmesh in case of model loading failures.
The logged message helps to pinpoint the root cause of unready condition.
Fix #100
Log a message in isReady check explaining the cause of NOT READY condition.
There are already logs for the other NOT READY conditions.
`Returning NOT READY to readiness probe due to unexpected model loading failures` is logged when there are model loading issues during startup.
> Log message on abortStartup due to unexpected model loading failures

- pom.xml
This is to move away from CVE-2024-23944: information disclosure.
> chore: Update zookeeper to 3.8.4

- .github/workflows/build.yml
Added linux/s390x ( platform ) in the build github workflow 
https://github.com/modassarrana89/modelmesh/actions/runs/8688245342/job/23823937204 // Build operation run in local workflow is a success. Attached archieve log for refernece
[logs_22763759557.zip](https://github.com/kserve/modelmesh/files/14978607/logs_22763759557.zip)
> feat: Add S390x support 

- config/base/kustomization.yaml
The main motivation for this update is to keep our manifests up to date with Kustomize v5. This ensures that we are using the latest syntax, which improves the compatibility and maintainability of our Kubernetes configurations.
- Added a replacements section to dynamically change values in the deployment configuration.
- Corrected the field path to ensure the replacement does not break when patches are used.
- Specifically, it replaces the environment variable value in the model-mesh deployment with the service name.
**Old Syntax:**
```
vars:
- name: MM_SERVICE_NAME
objref:
kind: Service
name: model-mesh
apiVersion: v1
fieldref:
fieldpath: metadata.name
```
**New Syntax:**
```
replacements:
- source:
kind: Service
name: model-mesh
fieldPath: metadata.name
targets:
- select:
kind: …
```
> chore: Update to Kustomize v5 syntax

- src/main/java/com/ibm/watson/modelmesh/payload/Payload.java
- src/main/java/com/ibm/watson/modelmesh/payload/RemotePayloadProcessor.java
Payload processor logs display the entirety of the `Payload`, including metadata and request contents.
This is not necessary at the log level.
> Remove unnecessary fields from ModelMesh logs

- pom.xml
chore:	Fix [CVE-2025-24970](https://github.com/advisories/GHSA-4g8c-wm8x-jfhw)
SslHandler doesn't correctly validate packets which can lead to native crash when using native SSLEngine
> Fix CVE-2025-24970
