kserve/modelmesh

config/README.md
config/base/kustomization.yaml
config/base/networkpolicy.yaml
pom.xml
src/main/java/com/ibm/watson/modelmesh/ModelCacheUnloadBufManager.java
src/main/java/com/ibm/watson/modelmesh/ModelLoader.java
src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
src/test/java/com/ibm/watson/modelmesh/AbstractModelMeshClusterTest.java
src/test/java/com/ibm/watson/modelmesh/DummyClassifierLoader.java
src/test/java/com/ibm/watson/modelmesh/DummyModelMesh.java
src/test/java/com/ibm/watson/modelmesh/ModelMeshEvictionsTest.java
src/test/java/com/ibm/watson/modelmesh/ModelMeshLoadFailureTest.java
src/test/java/com/ibm/watson/modelmesh/ModelMeshLoadPriorityTest.java
src/test/java/com/ibm/watson/modelmesh/ModelMeshTearDownTest.java
src/test/java/com/ibm/watson/modelmesh/ModelMeshTest.java
src/test/java/com/ibm/watson/modelmesh/ModelMeshZkFailTest.java

Pull in IBM-internal updates and fixes. We hope to soon be fully rebased on the kserve fork and will then be making such changes here directly.

Sync internal changes

---

src/main/java/com/ibm/watson/modelmesh/RateTracker.java
src/test/java/com/ibm/watson/modelmesh/util/InstanceStateUtil.java

While going through the modelmesh repo, found some lingering authors that weren't removed. Cleaning up leftovers authors.

chore: remove leftover authors

---

Dockerfile
pom.xml
src/main/java/com/ibm/watson/modelmesh/ModelCacheUnloadBufManager.java
src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
src/main/java/com/ibm/watson/modelmesh/ModelMeshEnvVars.java
src/main/java/com/ibm/watson/modelmesh/clhm/ConcurrentLinkedHashMap.java

**NOTE** Do not `/lgtm` this PR, make sure to rebase-and-merge.

Internal sync

---

pom.xml

- grpc-java `1.45.1`
- netty `4.1.75.Final`
- jackson-databind `2.13.2.2`

deps: Update grpc, netty, jackson-databind dependencies

---

pom.xml

deps: Upgrade netty to 4.1.77.Final

---

README.md

Many people have been asking for more detailed information about ModelMesh.
- Share charts covering details of the motivation, features, and design.
- Clarify how ModelMesh Serving builds on ModelMesh
We will aim to add more detailed documentation on how to use/configure the model-mesh container in a subsequent update.

docs: Minor README.md rewording and add link to charts

---

src/main/java/com/ibm/watson/modelmesh/ModelMesh.java

This PR includes some minor fixes/improvements noticed while working on other changes, some from IDE code inspection.
- Remove some redundant `@SuppressWarnings` annotations
- Make `CacheEntry#lastHeavyTime` field `volatile`
- Encapsulate dual use of `lastHeavyTime` field in access methods to improve readability
- Some additional precautionary null checks
- Move incorrectly placed break statement which would cause premature abortion of reaper registry processing loop in the event of a kv store request error
- Remove unused method parameter
Slightly cleaner and more correct code

misc: Miscellaneous small fixes / code improvements

---

pom.xml

gRPC, netty, protobuf, jackson-databind, eclipse-collections, log4j

deps: Refresh dependencies

---

pom.xml

grpc-java 1.49.0, netty 4.1.80.Final, protobuf 3.21.5

deps: Update grpc and netty dependencies

---

pom.xml

netty `4.1.82.Final`, grpc-java `1.49.1`, protobuf `3.21.6`, jackson-databind `2.13.4`, log4j `2.19.0`

deps: Update dependencies

---

pom.xml

Addresses protobuf-java CVE https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-h4h5-3hr4-j3g2

deps: Update protobuf and grpc dependencies

---

pom.xml

- netty `4.1.85.Final`
- grpc-java `1.51.0`
- jackson-databind `2.14.1`

deps: Update netty, grpc and jackson-databind libraries

---

pom.xml

deps: Update to latest protobuf version

---

pom.xml

grpc `1.54.1`, netty `4.1.92.Final`, protobuf `3.23.0`, tomcat-annotations-api `9.0.75`, jackson-databind `2.15.0`,  thrift `0.18.1`, junit `5.9.3`

chore: update dependencies to address vulnerabilities

---

pom.xml

Update netty `4.1.94.Final` and guava `32.0.1-jre`

chore: update dependencies to address CVEs

---

config/README.md

docs: fix typo

---

pom.xml

Cherry-picks https://github.com/red-hat-data-services/modelmesh/pull/8

Bump netty - CVE-2023-44487

---

.github/workflows/codeql.yml

Configure CodeQL vulnerability scans

chore: Configure CodeQL

---

pom.xml

chore: Fix [CVE-2024-30172](https://www.cve.org/CVERecord?id=CVE-2024-30172)

chore: Update bouncycastle 

---

Dockerfile

chore: Use latest ubi image tag

---

pom.xml

chore:	Fix CVE-2024-7254 com.google.protobuf:protobuf-java Stack-based Buffer Overflow

Fixes CVE-2024-7254

---

.github/workflows/build.yml
.github/workflows/codeql.yml
Dockerfile
pom.xml

chore:	Bump java version to 21 and base images from UBI8 to UBI9

Bump java to 21 and base images to ubi9
